// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgRNduKqkjfP3Zb8Zut5EYXtBwv4PkuD8',
    appId: '1:703036570353:web:06e8af4fe6113d28d04750',
    messagingSenderId: '703036570353',
    projectId: 'soochi-bbbc0',
    authDomain: 'soochi-bbbc0.firebaseapp.com',
    storageBucket: 'soochi-bbbc0.firebasestorage.app',
    measurementId: 'G-BR61F0JCTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgQ0fd0xVyqjRuE5jpj63k1KK3lkynGMo',
    appId: '1:703036570353:android:9f58a20d253c8ddcd04750',
    messagingSenderId: '703036570353',
    projectId: 'soochi-bbbc0',
    storageBucket: 'soochi-bbbc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3uDSq-n-Ys_4PJIYtqDVFIDSXqYIfJbE',
    appId: '1:703036570353:ios:14cde6d923e7f28ad04750',
    messagingSenderId: '703036570353',
    projectId: 'soochi-bbbc0',
    storageBucket: 'soochi-bbbc0.firebasestorage.app',
    iosBundleId: 'com.example.soochi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3uDSq-n-Ys_4PJIYtqDVFIDSXqYIfJbE',
    appId: '1:703036570353:ios:14cde6d923e7f28ad04750',
    messagingSenderId: '703036570353',
    projectId: 'soochi-bbbc0',
    storageBucket: 'soochi-bbbc0.firebasestorage.app',
    iosBundleId: 'com.example.soochi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgRNduKqkjfP3Zb8Zut5EYXtBwv4PkuD8',
    appId: '1:703036570353:web:8cf3e5ce30e52d1ed04750',
    messagingSenderId: '703036570353',
    projectId: 'soochi-bbbc0',
    authDomain: 'soochi-bbbc0.firebaseapp.com',
    storageBucket: 'soochi-bbbc0.firebasestorage.app',
    measurementId: 'G-E6D7B7TP2T',
  );
}
